---
functional:
  - Пользователи должны иметь возможность регистрироваться на сайте любым из перечисленных способом:с помощью никнейма, email и пароля, Discord, GitHub
  - Пользователи должны иметь возможность авторизоваться на сайте любым из перечисленных способом:с помощью никнейма, email и пароля, Discord, GitHub
  - Для участия в поединках пользователи должны авторизоваться через GItHub
  - Пользователи должны иметь возможность создавать битвы
  - Пользователи должны иметь возможность создавать турниры
  - Пользователи должны иметь возможность играть с реальным человеком, ботом или другом по ссылке
  - Пользователи могут выбирать для соревнований любой язык программирования из следующих:Clojure, C++, CSharp, Dart, Elixir, Golang, Java, JS, Kotlin, PHP, Python, Ruby, Rust, Swift, Zig, TS
  - Пользователи должны соревноваться на одинаковом языке программирования
  - Пользователи должны иметь возможность общаться друг с другом в чате
  - Пользователи должны иметь возможность наблюдать за турнирами в качестве зрителей
  - Пользователи должны иметь возможность создавать игру по уровню сложности, контролю времени, названию задачи или тегам 
  - Язык программирования должен быть выбран в процессе игры
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователям должна быть доступна для просмотра и сортировки турнирная таблица 
  - В карточке пользователя должны отображаться рейтинговые баллы
  - Пользователи, участвующие в турнире, должны одновременно видеть свой код и код соперника
  - Пользователи должны иметь возможность участвовать в пробной битве без регистрации
  - Пользователи должны иметь возможность сдаться во время игры
  
  
  
  
 
  
  




У виртуальных соперников (ботов) должны быть разные уровни скиллов: от elementary до hard




